id: P009298
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-19 19:32:10.569072
source_metadata:
  id: bdr:W1AC425
  title: 'རིག་འཛིན་འཇིགས་མེད་གླིང་པའི་རྣམ་ཐར་བསྡུས་མ། '
  author: ''
  volumes:
    89ecbed8a02148469eed22ce52e430e3:
      image_group_id: I2PD18723
      title: ''
      volume_number: 1
      total_pages: 152
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
